var viewporter;
(function(){var e=false;viewporter={ACTIVE:"ontouchstart"in window||/webos/i.test(navigator.userAgent),DEVICE_SUPPORTED:false,DEVICE_DENSITY:null,META_VIEWPORT_CONTENT:null,settings:{maxDensity:163},isLandscape:function(){return!e?window.orientation===90||window.orientation===-90:window.orientation===0||window.orientation===180},ready:function(a){window.addEventListener("viewportready",a,false)}};if(viewporter.ACTIVE){var d=function(){var a=this;this.data={};this.IS_ANDROID=/Android/.test(navigator.userAgent);document.addEventListener("DOMContentLoaded",
function(){a.computeViewportInformation();a.setMetaViewport();a.prepareVisualViewport();var b=window.orientation;window.addEventListener("orientationchange",function(){if(window.orientation!=b)a.computeViewportInformation(),a.updateMetaViewport(),a.prepareVisualViewport(),b=window.orientation},false)},false)};d.prototype={computeViewportInformation:function(){var a=this.getProfile();if(!a)return this.triggerWindowEvent("viewportunknown");e=a?a.inverseLandscape:false;var b=viewporter.isLandscape(),
c=0,d=1,f=!e?screen.height:screen.width,g=!e?screen.width:screen.height,i=this.IS_ANDROID?1:1/window.devicePixelRatio,c=0,j=false,k=f,l=g,h=function(a){return typeof a=="function"?a(k,l,d):a};if(c=typeof a.ppi=="function"?a.ppi():a.ppi)viewporter.DEVICE_DENSITY=c,viewporter.settings.maxDensity&&c>viewporter.settings.maxDensity&&(d*=viewporter.settings.maxDensity/c,i=this.IS_ANDROID?1:i/d);f=h(a.width)||f;g=h(a.height)||g;a.chromePrescale?(c=h(a.chromePrescale),j=true):c=h(a.chrome)||0;if(a=a[b?"landscape":
"portrait"])f=h(a.width)||f,g=h(a.height)||g,c=h(a.chrome)||c||0;this.data={width:(b?f:g)*d,height:(b?g:f)*d,scale:i,chromeHeight:c*(j?1:d)};viewporter.DEVICE_SUPPORTED=true},prepareVisualViewport:function(){var a=this,b=0,c=window.setInterval(function(){viewporter.DEVICE_SUPPORTED||a.maximizeDocumentElement();window.scrollTo(0,1);if(viewporter.DEVICE_SUPPORTED&&Math.abs(window.innerHeight-Math.ceil(a.data.height-a.data.chromeHeight))<5||b>10)clearInterval(c),a.triggerWindowEvent(!a._firstUpdateExecuted?
"viewportready":"viewportchange"),a._firstUpdateExecuted=true;b++},10)},triggerWindowEvent:function(a){var b=document.createEvent("Event");b.initEvent(a,false,false);window.dispatchEvent(b)},getProfile:function(){for(var a in viewporter.profiles)if(RegExp(a).test(navigator.userAgent))return viewporter.profiles[a];return null},maximizeDocumentElement:function(){document.documentElement.style.minHeight="5000px"},fixDocumentElement:function(a){document.documentElement.style.minHeight=(a||this.data.height-
this.data.chromeHeight)+"px";document.documentElement.style.minWidth=this.data.width+"px"},findMetaNode:function(a){for(var b=document.getElementsByTagName("meta"),c=0;c<b.length;c++)if(b[c].getAttribute("name")==a)return b[c];return null},setMetaViewport:function(){var a=this.findMetaNode("viewport")||document.createElement("meta");a.setAttribute("name","viewport");a.id="metaviewport";this.updateMetaViewport(a);document.getElementsByTagName("head")[0].appendChild(a)},updateMetaViewport:function(a){var a=
a||document.getElementById("metaviewport"),b=viewporter.DEVICE_SUPPORTED?["width="+this.data.width,"height="+(this.data.height-this.data.chromeHeight),"initial-scale="+this.data.scale,"minimum-scale="+this.data.scale,"maximum-scale="+this.data.scale]:["width=device-width","initial-scale=1","minimum-scale=1","maximum-scale=1"];this.IS_ANDROID&&b.unshift("target-densityDpi="+(viewporter.DEVICE_DENSITY?viewporter.settings.maxDensity||"device-dpi":"device-dpi"));viewporter.META_VIEWPORT_CONTENT=b.join(",");
a.setAttribute("content",viewporter.META_VIEWPORT_CONTENT);viewporter.DEVICE_SUPPORTED&&this.fixDocumentElement()}};new d}})();
viewporter.profiles={"iPhone|iPod":{ppi:function(){return window.devicePixelRatio>=2?326:163},width:function(e){return e*window.devicePixelRatio},height:function(e,d){return d*window.devicePixelRatio},chromePrescale:function(e,d,a){return window.devicePixelRatio>=2?(navigator.standalone?0:viewporter.isLandscape()?100:124)*a+2:(navigator.standalone?0:viewporter.isLandscape()?50:62)*a+2}},iPad:{ppi:132,chrome:function(){return navigator.standalone?0:/OS 5_/.test(navigator.userAgent)?96:78}},"GT-I9000|GT-I9100|Nexus S":{ppi:function(){if(/GT-I9000/.test(navigator.userAgent))return 239.3;
if(/GT-I9100/.test(navigator.userAgent))return 239.3;if(/Nexus S/.test(navigator.userAgent))return 239},width:800,height:480,chrome:38},MZ601:{ppi:160,portrait:{width:function(e,d){return d},height:function(e){return e}},chrome:152,inverseLandscape:true},"GT-P1000":{width:1024,height:600,portrait:{chrome:38}},"Desire_A8181|DesireHD_A9191":{width:800,height:480},TF101:{ppi:160,portrait:{width:function(e,d){return d},height:function(e){return e}},chrome:103,inverseLandscape:true}};